//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.19 at 05:01:15 PM IST 
//


package com.vehicle.identifier.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="frame" type="{http://com/vehicle/identifier/config}frame"/>
 *         &lt;sequence>
 *           &lt;element name="wheels" type="{http://com/vehicle/identifier/config}wheels"/>
 *         &lt;/sequence>
 *         &lt;element name="powertrain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "frame",
    "wheels",
    "powertrain"
})
@XmlRootElement(name = "vehicle")
public class Vehicle {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected Frame frame;
    @XmlElement(required = true)
    protected Wheels wheels;
    @XmlElement(required = true)
    protected String powertrain;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the frame property.
     * 
     * @return
     *     possible object is
     *     {@link Frame }
     *     
     */
    public Frame getFrame() {
        return frame;
    }

    /**
     * Sets the value of the frame property.
     * 
     * @param value
     *     allowed object is
     *     {@link Frame }
     *     
     */
    public void setFrame(Frame value) {
        this.frame = value;
    }

    /**
     * Gets the value of the wheels property.
     * 
     * @return
     *     possible object is
     *     {@link Wheels }
     *     
     */
    public Wheels getWheels() {
        return wheels;
    }

    /**
     * Sets the value of the wheels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Wheels }
     *     
     */
    public void setWheels(Wheels value) {
        this.wheels = value;
    }

    /**
     * Gets the value of the powertrain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPowertrain() {
        return powertrain;
    }

    /**
     * Sets the value of the powertrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPowertrain(String value) {
        this.powertrain = value;
    }

}
